<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="notation" nsURI="http://www.eclipse.org/glsp/notation"
    nsPrefix="notation">
  <eClassifiers xsi:type="ecore:EClass" name="Shape" eSuperTypes="#//NotationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="ecore:EClass ../../org.eclipse.glsp.graph/model/glsp-graph.ecore#//GPoint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="ecore:EClass ../../org.eclipse.glsp.graph/model/glsp-graph.ecore#//GDimension"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//NotationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendPoints" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.glsp.graph/model/glsp-graph.ecore#//GPoint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//NotationElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//NotationElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotationElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticElement" eType="#//SemanticElementReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//NotationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//NotationElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticElementReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedSemanticElement"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
